name: Release Drafter

on:
  push:
    branches:
      - dev
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    if: "!(github.head_ref == 'dev' && startsWith(github.base_ref, 'release/'))"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
